### PR TITLE
Project documentation - added one line description

### PR DESCRIPTION
**Pull request by anamaria2004**
### Pull Request Overview

I have added the one line description

### Testing Strategy

This pull request was tested by Ana-Maria Comeaga

### TODO or Help Wanted

Everything is the same as before.

### Build

- [ ] Ran `npm build`.

### Author

Signed-off-by: Ana-Maria Comeaga <anamariacomeaga@yahoo.com>

### CODE REVIEW

**Comment by alexandruradovici** [comment]
This is incorrect as you edited the old file. We renamed the file to *index.md*. Please update your repo and send the pr.

**Comment by anamaria2004** [comment]
> This is incorrect as you edited the old file. We renamed the file to _index.md_. Please update your repo and send the pr.

**Comment by anamaria2004** [comment]
It is all right now?

**Comment by alexandruradovici** [comment]
> It is all right now, @alexandruradovici? I have created another pull request.

Yes, closing this pull request as it is a duplicate.

**Pull request closed without merging**
