### PR TITLE
Final update 

### PR DESCRIPTION
**Pull request by RaduRadel**
### Pull Request Overview

This pull request adds the final version of the index.md file

### TODO or Help Wanted

This pull request still needs verification

### Build

- [ ] Ran `npm build`.

### Author

Signed-off-by: Radu-Costin BACCELA <baccelaradu4@gmail.com>

### CODE REVIEW

**Review by Gabi10017 — CHANGES_REQUESTED** [review]
Seems like you have duplicates of your pictures. Please delete the pictures you don't use.

**Comment by RaduRadel** [comment]
> Seems like you have duplicates of your pictures. Please delete the pictures you don't use.

i deleted the images that i dont use, but they are still in the "files changed" and appear in red. Is that a problem?
also the index.md looks strange in "files changed" but when i open the file it looks normal

**Comment by Gabi10017** [comment]
> > Seems like you have duplicates of your pictures. Please delete the pictures you don't use.
> 
> 
> 
> i deleted the images that i dont use, but they are still in the "files changed" and appear in red. Is that a problem?
> 
> also the index.md looks strange in "files changed" but when i open the file it looks normal
> 
> image
> 
> 

Yeah it seems like I was wrong. The only pictures remaining are the ones showing as Added, in green. The ones with `_new.jpeg`.

**Review by Gabi10017 — APPROVED** [review]

**Comment by Gabi10017** [comment]
This pull request is ready for review @alexandruradovici @irina-b-dev @ZamfirAndreiPaul @DTeodor-Alexaandru @TeodoraMiu @DanutAldea @irina-nita

**Comment by RaduRadel** [comment]
> > > Seems like you have duplicates of your pictures. Please delete the pictures you don't use.
> > 
> > 
> > i deleted the images that i dont use, but they are still in the "files changed" and appear in red. Is that a problem?
> > also the index.md looks strange in "files changed" but when i open the file it looks normal
> > image
> 
> Yeah it seems like I was wrong. The only pictures remaining are the ones showing as Added, in green. The ones with `_new.jpeg`.

I hope the pull request is ok right now, thank you

**Review by alexandruradovici — APPROVED** [review]

**Review by TeodoraMiu — APPROVED** [review]

**Pull request merged**
