### PR TITLE
Update to my project.

### PR DESCRIPTION
**Pull request by Angery-Stoman**
### Pull Request Overview

This pull request adds the hardware part of the project to my folder

### Testing Strategy

This pull request was tested by me

### TODO or Help Wanted

-Nothing left to do

### Build

- [x] Ran `npm build`.

### Author

Signed-off-by: Francu Teodor Matei <teodor_matei.francu@stud.fils.upb.ro>

### CODE REVIEW

**Comment by alexandruradovici** [comment]
Please fill the pull request template.

**Comment by Angery-Stoman** [comment]
I have edited the pull request to match the template offered

**Comment by alexandruradovici** [comment]
Your email is not in the template.

**Comment by Angery-Stoman** [comment]
I forgot to add it, I am sorry. It should be fine now

**Review by alexandruradovici — APPROVED** [review]

**Review by irina-b-dev — APPROVED** [review]

**Pull request merged**
