### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by Raluca3012**
Updated Hardware milestone
Signed-off-by: Mihaela-Raluca Dorobanțu <mihaela.dorobantu@stud.fils.upb.ro>

### CODE REVIEW

**Comment by alexandruradovici** [comment]
Please fix the build errors.

**Comment by kaanmeister** [comment]
The picture you tried to put on your `index.md` "SmartBot-Navigator_schematics.jpeg" is not on your project folder, you need to upload the picture to fix the build error.

**Comment by alexandruradovici** [comment]
Please fix the conflicts and the build errors.

**Comment by alexandruradovici** [comment]
@Raluca3012 please fix the conflicts as we cannot merge this.

**Comment by alexandruradovici** [comment]
The pull request is empty.

**Pull request closed without merging**
