### PR TITLE
KiCad and some updates of components and libraries

### PR DESCRIPTION
**Pull request by jacraul**
### Pull Request Overview

I changed the lcd 1602 to an OLED 0.91 inch cause the LCD had some problems, I also updated the library used for it. I added the photos with hardware (2 photos with all the components on breadboards) and I uploaded the KiCad schematics with all components connected to Pico RP2040W. 

### Testing Strategy

This pull request was tested by Raul Jac, all the components works properly so we are good to go to the software part.

### Author

Signed-off-by: Raul-Anton JAC <raul_anton.jac@stud.fils.upb.ro>

### CODE REVIEW

**Review by alexandruradovici — CHANGES_REQUESTED** [review]
Please move the kicad files to your project's repository.

**Comment by jacraul** [comment]
> Please move the kicad files to your project's repository.

without any new folder?

**Comment by alexandruradovici** [comment]
Please read carefully the Teams thread.

**Comment by alexandruradovici** [comment]
The kicad files should not be in this repository.

**Pull request closed without merging**
