### PR TITLE
Added Kicad files, hardware photos and updated the index

### PR DESCRIPTION
**Pull request by IonescuMariaMagdalena**
### Pull Request Overview

This pull request adds kicad files and hardware photos

### Testing Strategy

This pull request was tested by...

### TODO or Help Wanted

This pull request still needs to be checked

### Build

- [ ] Ran `npm build`.

### Author

Signed-off-by: Ionescu Maria-Magdalena <maria.ionescu0511@stud.fils.upb.ro>

### CODE REVIEW

**Comment by ZamfirAndreiPaul** [comment]
KiCad files needs to be uploaded on your github repository , not here. Keep only images and your index page.

**Comment by IonescuMariaMagdalena** [comment]
Can you check if it is ok now, please?

**Comment by IonescuMariaMagdalena** [comment]
I uploaded the Kicad files on my project repository

**Review by alexandruradovici — APPROVED** [review]

**Review by ZamfirAndreiPaul — APPROVED** [review]

**Comment by alexandruradovici** [comment]
Please resolve the conflicts.

**Review by alexandruradovici — APPROVED** [review]

**Review by alexandruradovici — APPROVED** [review]

**Review by irina-b-dev — APPROVED** [review]

**Pull request merged**
