### PR TITLE
Added KiCad schematic + Additional Hardware and Prototype pictures + LOG

### PR DESCRIPTION
**Pull request by kaanmeister**
### Pull Request Overview

This pull request has new pictures of hardware and prototype and the final looking. Added LOG. I have updated KiCad schematic regarding some changes and I uploaded the newest one. 

### Testing Strategy

This pull request was tested by Kaan UGUR

### TODO or Help Wanted

This pull request still needs...

### Build

- [ ] Ran `npm build`.

### Author

Signed-off-by: Kaan UGUR <kaanmeister.ro@gmail.com>

### CODE REVIEW

**Comment by alexandruradovici** [comment]
Please resolve the merge conflicts.

**Comment by kaanmeister** [comment]
> Please read about resolving git conflicts.

Resolved the conflicts and updated.

**Comment by kaanmeister** [comment]
I have finished the project and added final pictures of it. Added LOG + regarding some changes, I have updated KiCad folder, picture and uploaded.

**Comment by kaanmeister** [comment]
Re-opened the pull request in order to solve the build error.

**Comment by kaanmeister** [comment]
I fixed a code error on my branch and updated to solve the build error. Building has successfully completed.

**Review by alexandruradovici — CHANGES_REQUESTED** [review]
Please move the kicad project to your project's repository.

**Comment by alexandruradovici** [comment]
The kicad files are still on this branch.

**Comment by kaanmeister** [comment]
> The kicad files are still on this branch.

Yes, I am still trying to fix it. as soon as possible I fix the link, I will anounce here. Thank you so much for your time!

**Comment by kaanmeister** [comment]
Sorry for misunderstanding, I deleted and moved the KiCad folder to my project repository.

**Review by alexandruradovici — APPROVED** [review]

**Review by ZamfirAndreiPaul — APPROVED** [review]

**Pull request merged**
