### PR TITLE
Hardware update

### PR DESCRIPTION
**Pull request by Raluca3012**
Signed-off-by: Dorobanțu Mihaela-Raluca <mihaela.dorobantu@stud.fils.upb.ro>

### CODE REVIEW

**Comment by ZamfirAndreiPaul** [comment]
You must put the KiCad files in the repository, not here on the site.

**Review by alexandruradovici — CHANGES_REQUESTED** [review]
Please fill the pull request template.

**Comment by alexandruradovici** [comment]
> Please fill the pull request template.

This is not resolved yet.

**Comment by Raluca3012** [comment]
I filled the template

**Review by alexandruradovici — APPROVED** [review]

**Review by irina-b-dev — APPROVED** [review]

**Pull request merged**
