### PR TITLE
Project documentation

### PR DESCRIPTION
**Pull request by sadtoni**
Pull Request Overview
This pull request adds hardware schematic and completes the default template 
 Testing Strategy
This pull request was tested by Antonio GEORGESCU.

TODO or Help Wanted
This pull request needs feedback.

Build
 Ran npm build.
Author
Signed-off-by: Antonio GEORGESCU [georgescu.mihai.antonio@gmail.com](mailto:georgescu.mihai.antonio@gmail.com)

### CODE REVIEW

**Comment by sadtoni** [comment]
@alexandruradovici

**Comment by alexandruradovici** [comment]
Please fill the pull request template.

**Comment by sadtoni** [comment]
done @alexandruradovici

**Review by alexandruradovici — APPROVED** [review]

**Review by irina-b-dev — DISMISSED** [review]

**Comment by Gabi10017** [comment]
Please fix the conflicts, otherwise this pull-request cannot be merged.

**Comment by alexandruradovici** [comment]
@sadtoni

**Comment by sadtoni** [comment]
done @alexandruradovici @irina-b-dev

**Review by alexandruradovici — APPROVED** [review]

**Review by irina-b-dev — APPROVED** [review]

**Pull request merged**
