### PR TITLE
Update documentation + Hardware schematics"

### PR DESCRIPTION
**Pull request by MirceaAndrei**
### Pull Request Overview

This pull request adds Hardware schematics"

### Testing Strategy

This pull request was tested by Rata Mircea Andrei

### TODO or Help Wanted

This pull request still needs software part

### Build

- [ ] Ran `npm build`.

### Author

Signed-off-by: Rata Mircea Andrei <mircea.radu2003@gmail.com>

### CODE REVIEW

**Review by alexandruradovici — CHANGES_REQUESTED** [review]
Please move the kicad files to your project repository.

**Review by alexandruradovici — CHANGES_REQUESTED** [review]
Pleaae move the kicad project files to your repository.

**Comment by MirceaAndrei** [comment]
> Pleaae move the kicad project files to your repository.

I moved the Project kicad files.I dont know what else should i move.I put there all the Project files that I have în the specific folder.

**Comment by alexandruradovici** [comment]
Please read the guidelines that we wrote in the Teams channel. We do not merge kicad files here.

**Review by alexandruradovici — APPROVED** [review]

**Pull request merged**
